# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01b807a349860e78dfc45dd630bb0df50629b01add45a3f99d3243c1eecbe45af275191ca545e1a123e68f7b8be0d948639012e3c4779dd0c3837617ab06dcb3

test:
  secret_key_base: ca512cdfb9d63c1050aa17acecacbd18eb993800e12fb522886b2be6ebcd28be88a8296e92799ea56e2f0b24420dc6a95e5cbdd330042119727a0d4d7fd59aa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
